name: Build 3DS CIA Game

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm:latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Compile Code
        shell: bash
        run: |
          source /etc/profile.d/devkit-env.sh
          make

      - name: Create CIA Package
        shell: bash
        run: |
          source /etc/profile.d/devkit-env.sh
          bannertool makesmdh -s "Scarlet Skips" -l "Endless Jumper" -p "Dev" -o icon.smdh
          makerom -f cia -o ScarletSkips.cia -elf ScarletSkips.elf -rsf App.rsf -icon icon.smdh

      - name: Upload CIA File
        uses: actions/upload-artifact@v4
        with:
          name: ScarletSkips-CIA
          path: ScarletSkips.cia
